# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from detection/obstacle_bound.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class obstacle_bound(genpy.Message):
  _md5sum = "41b15b11d68bbfaa7472618894c283f6"
  _type = "detection/obstacle_bound"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 top_left_x
int16 top_left_y
int16 bottom_right_x
int16 bottom_right_y
float32 distance
"""
  __slots__ = ['top_left_x','top_left_y','bottom_right_x','bottom_right_y','distance']
  _slot_types = ['int16','int16','int16','int16','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       top_left_x,top_left_y,bottom_right_x,bottom_right_y,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(obstacle_bound, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.top_left_x is None:
        self.top_left_x = 0
      if self.top_left_y is None:
        self.top_left_y = 0
      if self.bottom_right_x is None:
        self.bottom_right_x = 0
      if self.bottom_right_y is None:
        self.bottom_right_y = 0
      if self.distance is None:
        self.distance = 0.
    else:
      self.top_left_x = 0
      self.top_left_y = 0
      self.bottom_right_x = 0
      self.bottom_right_y = 0
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4hf().pack(_x.top_left_x, _x.top_left_y, _x.bottom_right_x, _x.bottom_right_y, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.top_left_x, _x.top_left_y, _x.bottom_right_x, _x.bottom_right_y, _x.distance,) = _get_struct_4hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4hf().pack(_x.top_left_x, _x.top_left_y, _x.bottom_right_x, _x.bottom_right_y, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.top_left_x, _x.top_left_y, _x.bottom_right_x, _x.bottom_right_y, _x.distance,) = _get_struct_4hf().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4hf = None
def _get_struct_4hf():
    global _struct_4hf
    if _struct_4hf is None:
        _struct_4hf = struct.Struct("<4hf")
    return _struct_4hf
